# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: Property
    view:
        list: $/shohabbos/board/models/property/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/shohabbos/board/models/property/fields.yaml
        recordsPerPage: 10
