list: $/shohabbos/board/models/property/columns.yaml
modelClass: Shohabbos\Board\Models\Property
title: Properties
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/board/properties/update/:id'
