# ===================================
#  Relation Behavior Config
# ===================================

values:
    label: Value
    view:
        list: $/shohabbos/board/models/propertyvalue/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/shohabbos/board/models/propertyvalue/fields.yaml
        recordsPerPage: 10