plugin:
    name: 'shohabbos.board::lang.plugin.name'
    description: 'shohabbos.board::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-adjust
    homepage: ''
permissions:
    manage_categories:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage categories'
    manage_posts:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage posts'
    manage_properties:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage properties'
    mana_plans:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage plans'
navigation:
    board:
        label: Board
        url: shohabbos/board/posts
        icon: icon-life-ring
        permissions:
            - manage_posts
            - manage_categories
        sideMenu:
            board-posts:
                label: Posts
                url: shohabbos/board/posts
                icon: icon-sitemap
                permissions:
                    - manage_posts
            board-categories:
                label: Categories
                url: shohabbos/board/categories
                icon: icon-sitemap
                permissions:
                    - manage_categories
            board-properties:
                label: Properties
                url: shohabbos/board/properties
                icon: icon-sitemap
                permissions:
                    - manage_properties
            board-plans:
                label: Plans
                url: shohabbos/board/plans
                icon: icon-sitemap
                permissions:
                    - mana_plans
