plugin:
    name: 'shohabbos.board::lang.plugin.name'
    description: 'shohabbos.board::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-adjust
    homepage: ''
permissions:
    manage_categories:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage categories'
    manage_posts:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage posts'
    manage_properties:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage properties'
    manage_plans:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage plans'
    manage_locations:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage locations'
    manage_balance_history:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Balance history'
    manage_post_messages:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage post messages'
    manage_reviews:
        tab: 'shohabbos.board::lang.plugin.name'
        label: 'Manage reviews'
navigation:
    board:
        label: 'shohabbos.board::lang.menu.main_menu'
        url: shohabbos/board/posts
        icon: icon-life-ring
        permissions:
            - manage_posts
            - manage_categories
        sideMenu:
            board-posts:
                label: 'shohabbos.board::lang.menu.posts'
                url: shohabbos/board/posts
                icon: icon-align-justify
                permissions:
                    - manage_posts
            board-categories:
                label: 'shohabbos.board::lang.menu.categories'
                url: shohabbos/board/categories
                icon: icon-sitemap
                permissions:
                    - manage_categories
            board-properties:
                label: 'shohabbos.board::lang.menu.properties'
                url: shohabbos/board/properties
                icon: icon-plus
                permissions:
                    - manage_properties
            board-plans:
                label: 'shohabbos.board::lang.menu.plans'
                url: shohabbos/board/plans
                icon: icon-ticket
                permissions:
                    - mana_plans
            side-menu-item:
                label: 'shohabbos.board::lang.menu.locations'
                url: shohabbos/board/locations
                icon: icon-reorder
                permissions:
                    - manage_locations
            board-balance-history:
                label: 'История баланса'
                url: shohabbos/board/balancehistory
                icon: icon-history
                permissions:
                    - manage_balance_history
            board-post-messages:
                label: Жалобы
                url: shohabbos/board/postmessages
                icon: icon-slack
            pixel-reviews:
                label: Отзывы
                url: shohabbos/board/reviews
                icon: icon-star-half-empty
