list: $/shohabbos/board/models/post/columns.yaml
modelClass: Shohabbos\Board\Models\Post
title: Posts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/board/posts/update/:id'
