# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: Property Item
    view:
        list: $/shohabbos/board/models/postproperty/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/shohabbos/board/models/postproperty/fields.yaml
        recordsPerPage: 10
plans:
    label: Plan
    view:
        list: $/shohabbos/board/models/plan/columns.yaml
        toolbarButtons: link|unlink
    manage:
        form: $/shohabbos/board/models/plan/fields.yaml
        recordsPerPage: 10
        showSearch: true