title: Locations
modelClass: Shohabbos\Board\Models\Location
list: $/shohabbos/board/models/location/columns.yaml
recordUrl: 'shohabbos/board/locations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: 1
treeExpanded: 1
